/**
 * AUTO-GÉNÉRÉ — ne pas modifier à la main.
 * Source : docs/exercises-i18n-lexicon.md
 * Régénérer : node scripts/generateMotherSessionExerciseFr.mjs
 *
 * Lookup FR pour les noms d'exercices Mother Sessions, utilisé par le toggle
 * EN/FR (UserProfile.preferredLanguage). La clé est le nom EN normalisé
 * (lowercase + collapse whitespace + apostrophes/tirets uniformisés).
 */

export const MS_EXERCISE_FR_MAP: Record<string, string> = {
  "5-10-5 shuttle": "Shuttle 5-10-5",
  "90/90 hip switch": "Changement de hanche (90/90)",
  "a-skip": "A-skip",
  "ab wheel": "Roue abdominale",
  "acceleration to lateral shuffle to sprint": "Accélération + pas chassés latéraux + sprint",
  "adductor rock-back": "Rock-back adducteurs",
  "alternating db curl": "Curl haltères alterné",
  "ankle rocks": "Balancements de chevilles",
  "assisted neutral-grip pull-up": "Tractions prise neutre assistées",
  "back squat": "Back Squat",
  "band external rotation": "Rotation externe avec élastique",
  "band pressdown": "Pushdown élastique",
  "band pull-apart": "Tirage à l'élastique (écarté)",
  "band pull-apart or tyi light": "Tirage à l'élastique ou Élévation T-Y-I légère",
  "band-assisted split jump": "Split Jump assisté à l'élastique",
  "banded anderson box squat": "Anderson Box Squat avec bandes",
  "banded kb swing": "KB Swing avec bandes",
  "banded kettlebell swing": "Kettlebell Swing avec bandes",
  "banded neck extension": "Extension cervicale avec bande",
  "banded neck isometric": "Isométrie cervicale avec bande",
  "barbell hip thrust": "Hip Thrust barre",
  "barbell romanian deadlift": "Romanian Deadlift barre",
  "bear crawl": "Bear Crawl",
  "bench press": "Développé couché",
  "bird dog": "Bird Dog",
  "bodyweight split squat": "Fente bulgare au poids du corps",
  "bodyweight squat": "Squat au poids du corps",
  "box jump": "Saut sur box",
  "box squat": "Box Squat",
  "box-assisted goblet squat": "Goblet Squat assisté sur box",
  "broad jump": "Saut horizontal",
  "cable chop": "Chop à la poulie",
  "cable press": "Press à la poulie",
  "cable rotation explosive": "Rotation explosive à la poulie",
  "cable row": "Rowing poulie",
  "cable slam": "Slam à la poulie",
  "carry": "Marche chargée",
  "chest-supported row": "Rowing poitrine appuyée",
  "copenhagen hold": "Copenhagen Hold",
  "copenhagen plank": "Copenhagen Plank",
  "countermovement jump": "Countermovement Jump",
  "db bench press": "Développé couché haltères",
  "db incline bench press": "Développé incliné haltères",
  "db romanian deadlift": "Romanian Deadlift haltères",
  "dead bug": "Dead Bug",
  "depth push-up": "Pompes en profondeur",
  "drop jump": "Drop Jump",
  "drop to stick": "Drop & Stick",
  "explosive landmine press": "Landmine Press explosif",
  "face pull": "Face Pull",
  "farmer carry": "Farmer Carry",
  "football bar bench press": "Développé couché Football Bar",
  "free acceleration sprint": "Sprint d'accélération libre",
  "french press": "French Press",
  "front rack carry": "Front Rack Carry",
  "front squat": "Front Squat",
  "glute bridge": "Pont fessier",
  "goblet squat": "Goblet Squat",
  "hack squat": "Hack Squat",
  "half-kneeling cable row": "Rowing poulie demi-agenouillé",
  "half-kneeling landmine press": "Landmine Press demi-agenouillé",
  "hammer curl": "Hammer Curl",
  "hex bar rdl": "Romanian Deadlift Hex Bar",
  "hip thrust": "Hip Thrust",
  "incline db bench press": "Développé incliné haltères",
  "incline push-up": "Pompes inclinées",
  "inverted row": "Rowing inversé",
  "jump shrug": "Jump Shrug",
  "kettlebell swing": "Kettlebell Swing",
  "kickstand rdl": "Kickstand RDL",
  "landmine jammer": "Landmine Jammer",
  "landmine press": "Landmine Press",
  "landmine rotation": "Rotation Landmine",
  "landmine row": "Rowing Landmine",
  "lat pulldown": "Tirage vertical",
  "lateral bound": "Bond latéral",
  "lateral raise": "Élévations latérales",
  "leg extension": "Leg Extension",
  "leg press": "Presse à cuisses",
  "leg press calf press": "Mollets à la presse",
  "light sled push": "Poussée de traîneau légère",
  "low pogo hops": "Petits pogo hops",
  "lying leg curl": "Leg Curl allongé",
  "machine chest press": "Chest Press machine",
  "machine hack squat / leg press": "Hack Squat machine / Presse",
  "med ball chest pass": "Pass poitrine med ball",
  "med ball rotational throw": "Lancer rotationnel med ball",
  "med ball scoop throw": "Scoop Throw med ball",
  "med ball slam": "Med Ball Slam",
  "med ball throw": "Lancer med ball",
  "neck isometric": "Isométrie cervicale",
  "neutral-grip db bench press": "Développé haltères prise neutre",
  "neutral-grip lat pulldown": "Tirage vertical prise neutre",
  "neutral-grip pull-up": "Tractions prise neutre",
  "nordic curl": "Nordic Curl",
  "pallof": "Pallof",
  "pallof hold": "Maintien Pallof",
  "pallof press hold": "Maintien Pallof Press",
  "pendlay row": "Rowing Pendlay",
  "pin back squat": "Pin Back Squat",
  "pin squat": "Pin Squat",
  "plyo push-up": "Pompes pliométriques",
  "pogo hops": "Petits bonds sur pointes",
  "power pendlay row": "Pendlay Row explosif",
  "press-up exchange": "Échange en position pompe",
  "push press": "Push Press",
  "push-up": "Pompes",
  "rdl": "RDL",
  "reactive start to 45-degree cut": "Départ réactif + changement d'appui 45°",
  "rear-foot elevated split squat": "Split Squat pied arrière surélevé",
  "resisted acceleration": "Accélération résistée",
  "reverse lunge": "Fente arrière",
  "rope pressdown": "Pushdown corde",
  "safety bar squat": "Safety Bar Squat",
  "scap push-up": "Pompes scapulaires",
  "scapular control drill": "Drill contrôle scapulaire",
  "seated cable row": "Rowing poulie assis",
  "seated calf raise": "Mollets assis",
  "seated db overhead press": "Développé épaules haltères assis",
  "seated db press": "Développé haltères assis",
  "seated leg curl": "Leg Curl assis",
  "serratus reach": "Reach du dentelé",
  "short acceleration sprint": "Sprint court d'accélération",
  "short copenhagen hold": "Copenhagen Hold court",
  "side plank": "Gainage latéral",
  "single-arm db press": "Développé haltère unilatéral",
  "single-arm db row": "Rowing haltère un bras",
  "single-arm landmine press": "Landmine Press un bras",
  "single-leg bound": "Bond unipodal",
  "single-leg calf raise": "Mollet unilatéral",
  "single-leg glute bridge": "Pont fessier unilatéral",
  "single-leg rdl": "RDL unilatéral",
  "single-leg romanian deadlift": "Romanian Deadlift unilatéral",
  "skull crusher": "Skull Crusher",
  "sled push": "Poussée de traîneau",
  "split jump": "Split Jump",
  "split squat": "Split Squat",
  "split squat isometric hold": "Maintien isométrique en fente",
  "squat jump": "Squat Jump",
  "standing landmine press": "Landmine Press debout",
  "step-up": "Step-Up",
  "strict overhead press": "Overhead Press strict",
  "strict standing overhead press": "Overhead Press strict debout",
  "suitcase carry": "Suitcase Carry",
  "supine adductor squeeze": "Squeeze adducteurs allongé",
  "supine med ball throw": "Lancer med ball allongé",
  "t-bar row": "Rowing T-Bar",
  "t-y-i incline bench": "T-Y-I sur banc incliné",
  "thoracic rotation": "Rotation thoracique",
  "tibialis raise": "Tibialis Raise",
  "trap bar deadlift": "Soulevé de terre Trap Bar",
  "tyi light": "Élévation T-Y-I légère à l'élastique",
  "vertical jump": "Saut vertical",
  "wall drill march": "Montées de genoux contre le mur",
  "wall tibialis raise": "Tibialis Raise au mur",
  "weighted calf raise": "Mollets lestés",
  "world's greatest stretch": "World's Greatest Stretch",
  "zercher carry": "Zercher Carry",
}
