import type { WeeklySessionSlot } from '../../data/weeklyTemplates'
import { isBodyweightProgramTier } from './resolveEquipmentProgramTier'

/**
 * Mapping full_gym → bodyweight pour les mother sessions publiées.
 * Étendre au fur et à mesure de la conversion MD (Transition, Hyp, etc.).
 */
export const BODYWEIGHT_MOTHER_SESSION_ID_MAP: Readonly<Record<string, string>> = {
  FULL_OFFSEASON_RECOVERY_A_V1: 'FULL_BW_OFFSEASON_RECOVERY_A_V1',
  FULL_OFFSEASON_RECOVERY_B_V1: 'FULL_BW_OFFSEASON_RECOVERY_B_V1',
  LOWER_OFFSEASON_TRANSITION_V1: 'LOWER_BW_OFFSEASON_TRANSITION_V1',
  UPPER_OFFSEASON_TRANSITION_V1: 'UPPER_BW_OFFSEASON_TRANSITION_V1',
  FULL_OFFSEASON_TRANSITION_V1: 'FULL_BW_OFFSEASON_TRANSITION_V1',
  LOWER_OFFSEASON_HYPERTROPHY_V1: 'LOWER_BW_OFFSEASON_HYPERTROPHY_V1',
  UPPER_OFFSEASON_HYPERTROPHY_V1: 'UPPER_BW_OFFSEASON_HYPERTROPHY_V1',
  FULL_OFFSEASON_HYPERTROPHY_V1: 'FULL_BW_OFFSEASON_HYPERTROPHY_V1',
  LOWER_OFFSEASON_HYPERTROPHY_BACK_THREE_V1: 'LOWER_BW_OFFSEASON_HYPERTROPHY_V1',
  UPPER_OFFSEASON_HYPERTROPHY_BACK_THREE_V1: 'UPPER_BW_OFFSEASON_HYPERTROPHY_V1',
  FULL_OFFSEASON_HYPERTROPHY_BACK_THREE_V1: 'FULL_BW_OFFSEASON_HYPERTROPHY_V1',
  LOWER_OFFSEASON_FORCE_BRIDGE_V1: 'LOWER_BW_OFFSEASON_FORCE_BRIDGE_V1',
  UPPER_OFFSEASON_FORCE_BRIDGE_V1: 'UPPER_BW_OFFSEASON_FORCE_BRIDGE_V1',
  FULL_OFFSEASON_FORCE_BRIDGE_V1: 'FULL_BW_OFFSEASON_FORCE_BRIDGE_V1',
  LOWER_OFFSEASON_FORCE_BRIDGE_BACK_THREE_V1: 'LOWER_BW_OFFSEASON_FORCE_BRIDGE_V1',
  UPPER_OFFSEASON_FORCE_BRIDGE_BACK_THREE_V1: 'UPPER_BW_OFFSEASON_FORCE_BRIDGE_V1',
  FULL_OFFSEASON_FORCE_BRIDGE_BACK_THREE_V1: 'FULL_BW_OFFSEASON_FORCE_BRIDGE_V1',
  LOWER_IN_SEASON_FRONT_ROW_V1: 'LOWER_BW_IN_SEASON_V1',
  LOWER_IN_SEASON_BACK_THREE_V1: 'LOWER_BW_IN_SEASON_V1',
  UPPER_IN_SEASON_FRONT_ROW_V1: 'UPPER_BW_IN_SEASON_V1',
  UPPER_IN_SEASON_BACK_THREE_V1: 'UPPER_BW_IN_SEASON_V1',
  LOWER_PRESEASON_FORCE_V1: 'LOWER_BW_PRESEASON_FORCE_V1',
  UPPER_PRESEASON_FORCE_V1: 'UPPER_BW_PRESEASON_FORCE_V1',
  FULL_PRESEASON_FORCE_V1: 'FULL_BW_PRESEASON_FORCE_V1',
  SPEED_POWER_PRESEASON_INTRO_V1: 'SPEED_BW_POWER_PRESEASON_INTRO_V1',
  LOWER_PRESEASON_FORCE_POWER_V1: 'LOWER_BW_PRESEASON_FORCE_POWER_V1',
  UPPER_PRESEASON_FORCE_POWER_V1: 'UPPER_BW_PRESEASON_FORCE_POWER_V1',
  FULL_PRESEASON_FORCE_POWER_V1: 'FULL_BW_PRESEASON_FORCE_POWER_V1',
  SPEED_POWER_PRESEASON_V1: 'SPEED_BW_POWER_PRESEASON_V1',
  LOWER_PRESEASON_POWER_FRONT_ROW_V1: 'LOWER_BW_PRESEASON_POWER_V1',
  LOWER_PRESEASON_POWER_BACK_THREE_V1: 'LOWER_BW_PRESEASON_POWER_V1',
  UPPER_PRESEASON_POWER_FRONT_ROW_V1: 'UPPER_BW_PRESEASON_POWER_V1',
  UPPER_PRESEASON_POWER_BACK_THREE_V1: 'UPPER_BW_PRESEASON_POWER_V1',
  FULL_PRESEASON_POWER_FRONT_ROW_V1: 'FULL_BW_PRESEASON_POWER_V1',
  FULL_PRESEASON_POWER_BACK_THREE_V1: 'FULL_BW_PRESEASON_POWER_V1',
  FULL_BODY_IN_SEASON_FRONT_ROW_V1: 'FULL_BW_BODY_IN_SEASON_V1',
  FULL_BODY_IN_SEASON_BACK_THREE_V1: 'FULL_BW_BODY_IN_SEASON_V1',
  FULL_LIGHT_PRIMER_IN_SEASON_FRONT_ROW_V1: 'FULL_BW_LIGHT_PRIMER_IN_SEASON_V1',
  FULL_LIGHT_PRIMER_IN_SEASON_BACK_THREE_V1: 'FULL_BW_LIGHT_PRIMER_IN_SEASON_V1',
}

export function mapMotherSessionIdForEquipment(
  sessionId: string,
  equipment: string[] | undefined,
): string {
  if (!isBodyweightProgramTier(equipment as never)) return sessionId
  return BODYWEIGHT_MOTHER_SESSION_ID_MAP[sessionId] ?? sessionId
}

export function mapWeeklySlotsForEquipment(
  slots: WeeklySessionSlot[],
  equipment: string[] | undefined,
): WeeklySessionSlot[] {
  return slots.map((slot) => ({
    ...slot,
    sessionId: mapMotherSessionIdForEquipment(slot.sessionId, equipment),
  }))
}

export function bodyweightSessionFallbackWarning(
  originalSessionId: string,
  mappedSessionId: string,
  equipment: string[] | undefined,
): string | undefined {
  if (!isBodyweightProgramTier(equipment as never)) return undefined
  if (originalSessionId !== mappedSessionId) return undefined
  if (originalSessionId in BODYWEIGHT_MOTHER_SESSION_ID_MAP) return undefined
  if (originalSessionId.includes('_BW_')) return undefined
  return `Séance ${originalSessionId} : version poids de corps non encore publiée — contenu salle affiché.`
}
